### ISSUE TITLE
README clarifications and suggestions

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/policy-automation#10]
### L48 - Requirements Section
- Add requirement of "ConjurHostsPlugin.zip" from Support Vault > CyberArk Conjur safe.

### L59
- Provide location to CPM Plugin (or reference Requirements section)

### L67
- Key is `AccountName` not `Account`

### L75 - Configuring Conjur Policy Section
- Add explanation of Jinja variables within policy
  - {{ SyncHostName }}
  - {{ vault-id }}

### L81
- Give guidance on what safe (if relevant) to onboard account to
  - After onboarding to a separate safe, it should've just gone in the VaultConjurSync safe
- Give example values for Account properties to provide when onboarding account
  - Address syntax (e.g. https:// or no https://)
  - Host syntax (e.g. host/ or no host/)

### L92
Use code block (encapsulated `) instead of quoting

### L105
- Specify it should be the CyberArk User and not the Host Identity onboarded into EPV for Conjur
- Provide guidance on how to create a new CyberArk User instead of using the pre-existing Sync_ user

### L131
- Provide initial example value for better clarification

### Missing Pieces

- Created an Application ID, but never applied it to any safe based on documentation.
- Guidance on how to automate script triggering is missing. (Scheduled task or whatever)
- Review of first safe (Hello World safe) & configuration to allow policy automation.

**Comment by infamousjoeg** [comment]
@aharriscybr

**Comment by ztwright** [comment]
@aharriscybr Can you please assign me to this issue?

**Comment by aharriscybr** [comment]
@ztwright all yours!
