### ISSUE TITLE
Add proper -ErrorAction to prevent continuing after error occurs

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/policy-automation#16]
When encountering an error in the onboarding-service.ps1 script, the script continues to execute instead of stopping at the error.  Using the parameter `-ErrorAction` with the value `Stop` will allow the script to exit properly when an error occurs.

**Comment by aharriscybr** [comment]
@infamousjoeg,

Which error did you run into while running?

**Comment by infamousjoeg** [comment]
![image](https://user-images.githubusercontent.com/1924063/199762630-58679014-9be4-45db-9914-612366ad1779.png)

It was caused by me.  But made me aware to this.  Addt'l commit to current PR incoming.
