### ISSUE TITLE
Lingering hosts after failing to vault

### ISSUE THREAD

**Issue by DornIdentity** [conjurdemos/policy-automation#18]
Current behavior:
-when the !host is created in Conjur but the script fails to vault it, the !host remains in Conjur. This means the host has to be manually deleted via policy before the script can properly entitle it and vault it.

Proposed fix:
- Delete the !host when it fails to vault.

**Comment by aharriscybr** [comment]
@DornIdentity Let's review the logging added for this feature, we need to ensure there's sufficient logging to identify this host doesn't get stuck in limbo and we can identify there is a problem.
